### ISSUE TITLE
Fatal Error [4.0]

### ISSUE THREAD

**Issue by tobiaskirchmaier** [poggit/devirion#20] opened 2021-11-03 10:05 UTC
Pocketmine-Version: `pocketmine/pocketmine-mp:4.0.0-BETA9`, `pocketmine/pocketmine-mp:4.0.0-BETA10`
```
Fatal error: Declaration of poggit\virion\devirion\VirionClassLoader::loadClass($name): ?bool must be compatible with
BaseClassLoader::loadClass(string $name): bool in C:\xampp\home\servers\Server-2\plugins\devirion\src\poggit\virion\devirion\VirionClassLoader.php on line 86
```

> ClassLoader dependency has been updated to [`pocketmine/classloader` v0.2.0](https://github.com/pmmp/ClassLoader/tree/0.2.0)

**Comment by KygekDev** [comment] 2021-11-03 10:47
Same issue here.

I'm hoping it will be fixed ASAP because I use DEVirion for plugin development.

**Comment by KygekDev** [comment] 2021-11-03 10:58
I think we need to make a BC break because we can no longer return `null` when an exception gets thrown from `parent::loadClass()`.

https://github.com/poggit/devirion/blob/3d01606412c19ca8c0b21ac3e201d4599140c39c/src/poggit/virion/devirion/VirionClassLoader.php#L86-L92

I will let the Poggit maintainers to decide what thing to BC break, because it's not my right to decide.

**Comment by ColinHDev** [comment] 2021-11-03 12:01
(Caused by https://github.com/pmmp/ClassLoader/commit/af7e2704f80cedfcefba5042cf2b980d13eb98bb)

**Comment by KygekDev** [comment] 2021-11-12 11:09
@SOF3 please close this issue, thanks.

**Closed as completed** 2021-11-13 05:27 UTC
